# Generated by Django 4.2.26 on 2025-11-16 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='whiteman_word_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whiteman_games', to='game.wordgroup'),
        ),
        migrations.AlterField(
            model_name='game',
            name='word_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citizen_impostor_games', to='game.wordgroup'),
        ),
    ]
