# Generated by hand on 2025-11-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_game_whiteman_word_group_alter_game_word_group'),
        ('game', '0003_nudge'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    'ALTER TABLE "game_game" ADD COLUMN IF NOT EXISTS "actual_num_impostors" integer NOT NULL DEFAULT 0;',
                    reverse_sql='ALTER TABLE "game_game" DROP COLUMN IF EXISTS "actual_num_impostors";'
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='game',
                    name='actual_num_impostors',
                    field=models.IntegerField(default=0),
                ),
            ]
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    'ALTER TABLE "game_game" ADD COLUMN IF NOT EXISTS "actual_num_whitemen" integer NOT NULL DEFAULT 0;',
                    reverse_sql='ALTER TABLE "game_game" DROP COLUMN IF EXISTS "actual_num_whitemen";'
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='game',
                    name='actual_num_whitemen',
                    field=models.IntegerField(default=0),
                ),
            ]
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    'ALTER TABLE "game_nudge" ADD COLUMN IF NOT EXISTS "round_number" integer NOT NULL DEFAULT 0;',
                    reverse_sql='ALTER TABLE "game_nudge" DROP COLUMN IF EXISTS "round_number";'
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='nudge',
                    name='round_number',
                    field=models.IntegerField(default=0),
                ),
            ]
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    'ALTER TABLE "game_player" ADD COLUMN IF NOT EXISTS "nudge_meter" integer NOT NULL DEFAULT 0;',
                    reverse_sql='ALTER TABLE "game_player" DROP COLUMN IF EXISTS "nudge_meter";'
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='player',
                    name='nudge_meter',
                    field=models.IntegerField(default=0),
                ),
            ]
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    'ALTER TABLE "game_player" ADD COLUMN IF NOT EXISTS "nudge_meter_round" integer NOT NULL DEFAULT 0;',
                    reverse_sql='ALTER TABLE "game_player" DROP COLUMN IF EXISTS "nudge_meter_round";'
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='player',
                    name='nudge_meter_round',
                    field=models.IntegerField(default=0),
                ),
            ]
        ),
    ]
