# Generated by Django 4.2.26 on 2025-11-16 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_game_whiteman_word_group_alter_game_word_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nudge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged', models.BooleanField(default=False)),
                ('from_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nudges_sent', to='game.player')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nudges', to='game.game')),
                ('to_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nudges_received', to='game.player')),
            ],
            options={
                'verbose_name': 'Nudge',
                'verbose_name_plural': 'Nudges',
            },
        ),
    ]
