# Generated by Django 4.2.26 on 2025-11-18 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_add_actual_counts_and_nudge_fields'),
        ('game', '0004_actual_counts_and_nudge_fields'),
    ]

    operations = [
    ]
