# Generated by Django 4.2.26 on 2025-11-18 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_merge_20251117_2312'),
        ('game', '0005_nudge_meter_hp_defaults'),
    ]

    operations = [
    ]
