# Generated by Django 4.2.26 on 2025-11-18 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_merge_20251117_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='nudge_meter',
            field=models.IntegerField(default=100),
        ),
    ]
