# Generated by Django 4.2.26 on 2025-11-20 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_chaos_power_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='palhaco_goal_state',
            field=models.CharField(blank=True, choices=[('', 'Sem Objetivo'), ('finding', 'Encontrando Impostor'), ('pending', 'Aguardando Atualização'), ('eliminate', 'Precisa ser Eliminado')], default='', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('game', 'voter', 'target', 'round_number', 'is_palhaco_guess')},
        ),
    ]
