# Generated by Django 4.2.26 on 2025-11-18 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_merge_20251117_2312'),
        ('game', '0008_clown_role_and_white_ghost'),
    ]

    operations = [
    ]
